### ISSUE TITLE
Non-breaking space `&nbsp;` in ADoc goes missing in XML (and subsequent formats)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#712]
> Can't find the “ISO8000” text.

This is actually present:
```adoc
To support the delivery of high-quality data, the ISO&nbsp;8000 series addresses:
```

PDF:
<img width="409" alt="Screenshot 2022-05-29 at 9 32 41 PM" src="https://user-images.githubusercontent.com/11865/170871503-b83f93ee-ea87-4777-b1f9-8e7449163be4.png">

DOC:
<img width="569" alt="Screenshot 2022-05-29 at 9 33 36 PM" src="https://user-images.githubusercontent.com/11865/170871550-415720cc-669c-476d-922d-c6766faa2aa4.png">

XML:
```xml
<p id="...">To support the delivery of high-quality data, the ISO8000 series addresses:</p>
```

There is an nbsp there, but in rendering it is not given at all.

_Originally posted by @ronaldtse in https://github.com/metanorma/iso-8000-118/issues/3#issuecomment-1140450894_

**Comment by opoudjis** [comment]
This is a consequence of the move to Nokogiri 1.13, which does not recognise HTML named escapes, and I have preprocessing to convert any such escapes in input Asciidoc into numbered escapes. I'd have to investigate why that is failing, but your workaround is to use `&#xa0;`.

**Comment by opoudjis** [comment]
Restored 

````
To support the delivery of high-quality data, the ISO&nbsp;8000 series addresses:
````

I cannot replicate: the XML (which no longer has numbered entities because of the clusterfuck of mapping in and out) has a nonbreaking space there, and that propagates through to DOC:

<img width="635" alt="Στιγμιότυπο 2022-05-30, 21 51 28" src="https://user-images.githubusercontent.com/1911039/170986741-d7dcd5f8-dc0e-4094-840b-1c47aaf3a123.png">

<img width="635" alt="Στιγμιότυπο 2022-05-30, 21 50 52" src="https://user-images.githubusercontent.com/1911039/170986776-3a9a9d9c-c13b-46b5-8155-3f6ac3ed1a9b.png">

This was fixed in the current release, from https://github.com/metanorma/metanorma-standoc/pull/630

Strongly recommend you refresh and recompile.

**Comment by ronaldtse** [comment]
I have just done that, with the latest released gems.
PDF still shows the issue.
<img width="584" alt="Screenshot 2022-05-30 at 10 08 35 PM" src="https://user-images.githubusercontent.com/11865/171009337-fa04945f-acc4-4e06-881f-0d41f855cd53.png">

**Comment by ronaldtse** [comment]
Using the latest git gems does solve the issue (isodoc, metanorma-iso, metanorma-standoc). Thanks! Closing.
<img width="569" alt="Screenshot 2022-05-30 at 10 11 42 PM" src="https://user-images.githubusercontent.com/11865/171009832-3a540875-07f4-4e90-b40a-32235c98ccea.png">
